JsonParserで\がエスケープ対象に認識されず、以降が全てエスケープ文字として扱われるバグを解消
nablarch/nablarch-core-dataformat pull request #74
Opened 2024-02-21 10:09 UTC by kankichi00

JsonParserのアンエスケープ処理に関して、タイトルのバグの解消とテストの網羅性の見直しを行いました。
見直しの結果、\がuXXXX形式でパースを行うとエラーが発生するバグも見つかったので解消しました。

2024-02-21 12:19 UTC, kumagoro1202 requested changes

2024-02-21 12:19 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("nquotSl", "\n/");
ここも省略によって何を表してるのかわからないのと、既存部分が連番のkey1～key9なのに途中から命名規則が変わることで読みにくくなっています。既存部分も合わせて整理して制御文字がvalueの最初にある場合、中間にある場合、最後にある場合とそれらが重複する場合で網羅性がわかりやすくなるようにしてください。

2024-02-22 08:54 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +        MatcherAssert.assertThat(result, is(expectedMap));
staticインポートに変更しました。

2024-02-22 08:54 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("bs", "\b");
単体のテストに関して、略さない名前に変更しました。

2024-02-22 08:54 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +    public void testSimpleUnescape() throws Exception {
singleに修正しました。

2024-02-22 08:55 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("slash", "/");
可読性向上のため、キーの名前をご指摘の通り変更しました。

2024-02-22 08:55 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("nquotSl", "\n/");
全体的に網羅性を見直しました。一部テストの修正とコメントの追加を行いました。

2024-02-22 11:30 UTC, kumagoro1202 requested changes

2024-02-22 11:30 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("unescapedSolidus", "/");
最初文字数揃えてくれてたみたいにスペースでインデント付けてくれた方が見やすいかもとは思いました。修正はマストではないですが。
```
                    put("quotationMark"   , "\"");
                    put("reverseSolidus"  , "\\");
                    put("escapedSolidus"  , "/");
                    put("backspace"       , "\b");
                    put("formFeed"        , "\f");
                    put("lineFeed"        , "\n");
                    put("carriageReturn"  , "\r");
                    put("tab"             , "\t");
                    put("unescapedSolidus", "/");
```

2024-02-22 11:30 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +         * */
> \以外の/、b、f、n、r、tは同じ分岐で処理をしている

`\"`と`\n`を両方やるのは何故でしたっけ？
`\`とそれ以外の制御文字でいいのではと思ったので質問。

2024-02-22 11:30 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("multipleEscape2", "\"\\\b\f\n\r\t");
ここはもうちょっと観点細かいと思います。制御文字になりえないものと制御文字、エスケープされたリテラルとしての制御文字の組み合わせに分かれるのでは？「複数回エスケープシーケンスが存在する場合」というのは少し乱暴過ぎる気がしました。

2024-02-22 11:30 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    // "\b"を代表値とし、検証できれば他の、仕様上f,n,r,tも同様に扱われるので省略する。
> 検証できれば他の、仕様上f,n,r,tも

「他の」はなくていいと思います。

2024-02-26 01:56 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +         * */
元々は、`\"`はエスケープされているとき、クオート開始、終了と挙動が他のものと違うのでテストする必要があると考えていました。

ただ改めて考えると、他のテストパターンで網羅されていて、`\"`と`\n`を両方やることで洗い出せるテストケースはなかったので、`\"`のみテストするように修正しました。

2024-02-26 01:57 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("multipleEscape2", "\"\\\b\f\n\r\t");
観点を見直し、細かく分割しました。

2024-02-26 01:57 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    // "\b"を代表値とし、検証できれば他の、仕様上f,n,r,tも同様に扱われるので省略する。
「他の」を削除しました。

2024-02-26 01:57 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("unescapedSolidus", "/");
インデントを入れ、修正しました。

2024-02-27 12:42 UTC, kumagoro1202 requested changes

2024-02-27 12:42 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +         * 一つ検証＋それぞれのエスケープシーケンスについて単体で検証済みなら他についても検証される。
> 実装上、パースをおこなっている分岐は\の後"、\以外の/、b、f、n、r、tは同じ分岐で処理をしているため、

この文章の意味が読み取れませんでした。\でエスケープが始まり、エスケープ対象として\の分岐と、/、b、f、n、r、tの分岐に分かれている。そのため\と、同じ分岐で処理されるもののうち"を代表例として検証を行うという意味？「\の後"、\以外の」となってますが"は後ろのやつらと同じ分岐では？日本語が間違っているように見えるので確認お願いします。
3行めの「一つ検証＋それぞれのエスケープシーケンス」というのも、「同じ分岐で処理されるものから代表例を一つエスケープシーケンスが連続するパターンを検証し、それ以外のエスケープ対象については単体で～」という意味ですかね？

2024-02-27 12:42 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    // エスケープシーケンスになりえない文字と、"\"の直後に置くとエスケープシーケンスになる文字(b,f,n,r,t)を含んだエスケープシーケンスが複数回存在する場合
全体的に観点を書く場合は合格条件もセットで書いてもらった方がいいです。
「エスケープシーケンスになりえない文字(a)とエスケープシーケンスのセットが複数回出現する場合にそれぞれがエスケープシーケンスとして解析されること」とか。
あとmultipleEscapeString1は上記の観点かと思いますが、multipleEscapeString2は上記の観点に加えてエスケープされたバックスラッシュが前についててもエスケープシーケンスとして解析されることという観点も入ってるのかなと思いました。

2024-02-27 12:42 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("multipleUnescapeString2", "a\\\\b a\\\\f a\\\\n a\\\\r a\\\\t");
こっちはエスケープされたバックスラッシュが前にあってもエスケープシーケンスになりうる文字がリテラルとして解析されることとかですかね。

2024-02-27 12:42 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("multipleEscapeSymbols3", "a\\\\\" a\\\\\\ a\\\\/");
multipleEscapeString1とmultipleEscapeSymbols1との観点の違いがよくわからないです。
既存のテストケースを残す必要はないのできちんと観点を整理してそれを代表するようなわかりやすいテストケースにしてほしいです。今のテストケースの作り方は整理してからそれにあったパターンを作るのではなく、既存のパターンありきでそれを残すために観点を無理やり作ってる感じに見えます。追加してもらった388行目～421行目のパターンで網羅できてないのってどういう観点でしょうか？それを網羅するために必要なパターンってどういうものでしょうか？

2024-02-27 12:42 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    // 開始位置に"\\"が存在する場合に、b,f,n,r,tはエスケープシーケンスとしてではなく、文字として扱われることを確認する。
（これは指摘じゃなく感想）
ここは観点に合格条件も含まれているので読んでよく理解できました。

2024-02-28 09:37 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +         * 一つ検証＋それぞれのエスケープシーケンスについて単体で検証済みなら他についても検証される。
> 「\の後"、\以外の」となってますが"は後ろのやつらと同じ分岐では？

実装と仕様と観点がごっちゃになっていましたが、エスケープ処理に関して同じ分岐なので、以下の通り文言を修正しました。

1文字目のエスケープシーケンスはどれでも違いはないため、代表値として固有の処理がある「/"」と「//」を使用する。

2024-02-28 09:38 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    // エスケープシーケンスになりえない文字と、"\"の直後に置くとエスケープシーケンスになる文字(b,f,n,r,t)を含んだエスケープシーケンスが複数回存在する場合
全体的に合格条件をJavadocに追加しました。
また網羅性を見直し、既存のテストを削除し、一部テストを追加しました。

2024-02-28 09:39 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("multipleUnescapeString2", "a\\\\b a\\\\f a\\\\n a\\\\r a\\\\t");
追加テストで検証済みな観点のため、既存テストは削除しました。

2024-02-28 09:39 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("multipleEscapeSymbols3", "a\\\\\" a\\\\\\ a\\\\/");
追加テストで検証済みな観点のため、既存テストは削除しました。

2024-02-28 09:39 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    // 開始位置に"\\"が存在する場合に、b,f,n,r,tはエスケープシーケンスとしてではなく、文字として扱われることを確認する。
全てに合格条件を含めるよう心がけます。

2024-02-28 11:27 UTC, kumagoro1202 requested changes

2024-02-28 11:27 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +     * 1文字目のエスケープシーケンスはどれでも違いはないため、代表値として固有の処理がある「/"」と「//」を使用する。
> 「/"」と「//」を使用する。

\"と\\の誤り？

2024-02-28 11:27 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                     * RS → reverseSolidusj
typo
最後に不要なjがある。

2024-02-28 11:27 UTC, kumagoro1202 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("fullNewLine", "a");
fullってどういう意味で使ってますか？ホワイトスペース（orタブ）が挿入されうる位置全部という意味？
fullWhiteSpaceと書かれると真っ先に思い浮かぶのはfull-widthなWhiteSpaceだと思うので、文字のパースとかの文脈ではあまり適切な命名ではないかなと思いました。最初全角の空白が入っているのかなと思ってしまいました。
withWhiteSpaceとかincludeWhiteSpaceとかの方がしっくりくると思います。

2024-02-29 06:53 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +     * 1文字目のエスケープシーケンスはどれでも違いはないため、代表値として固有の処理がある「/"」と「//」を使用する。
"と\に修正しました。

2024-02-29 06:53 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                     * RS → reverseSolidusj
修正しました。

2024-02-29 06:53 UTC, kankichi00 commented on src/test/java/nablarch/core/util/JsonParserTest.java
> +                    put("fullNewLine", "a");
include～に修正しました。

2024-03-01 01:10 UTC, kumagoro1202 approved these changes

2024-03-01 01:10 UTC, merged